// Auto-generated by the Load Impact converter

import "../libs/shim/core.js";

export let options = {duration: "10m", maxRedirects: 4, iterations: "500", target: 500};

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
    options
});

export default function () {
    postman[Request]({
        name: "list ruleset",
        id: "3278f6f6-9389-44bd-add9-e9ee1df6179b",
        method: "GET",
        address: "http://localhost:3000/api/v1/rulesets"
    });

    postman[Request]({
        name: "delete ruleset",
        id: "3431c901-4b41-4f25-8c83-601e7d129345",
        method: "DELETE",
        address:
            "http://localhost:3000/api/v1/rulesets/51c1563d-95e8-4d24-95db-4c79e2d7d287"
    });

    postman[Request]({
        name: "create ruleset",
        id: "e02a7abd-1c27-44de-86d5-addb53796ba0",
        method: "POST",
        address: "http://localhost:3000/api/v1/rulesets",
        data:
            '{\n\t"Name": "test_ruleset_2",\n    "StartDate": "2019-08-11T05:21:10+05:21",\n\t"EndDate": "2019-08-14T05:21:10+05:21",\n\t"Enable": true,\n\t"Rules": [{\n\t\t"Name":"rule1",\n        "Enable": true,\n        "WhenConditions": [\n        \t{\n        \t\t"Field1": "field1", \n        \t\t"Field2": "35", \n        \t\t"Operator": ">"\n        \t}],\n        "ThenActions": [\n        \t{\n        \t\t"Field1": "cashback", \n        \t\t"Operator": "=",\n        \t\t"value": "10"\n        \t}]\n\t},\n\t{\n\t\t"Name":"rule2",\n        "Enable": true,\n        "WhenConditions": [\n        \t{\n        \t\t"Field1": "field1", \n        \t\t"Field2": "75", \n        \t\t"Operator": ">"\n        \t}],\n        "ThenActions": [\n        \t{\n        \t\t"Field1": "cashback", \n        \t\t"Operator": "=",\n        \t\t"value": "10"\n        \t}]\n\t},\n\t{\n\t\t"Name":"rule3",\n        "Enable": true,\n        "WhenConditions": [\n        \t{\n        \t\t"Field1": "field1", \n        \t\t"Field2": "100", \n        \t\t"Operator": "<"\n        \t}],\n        "ThenActions": [\n        \t{\n        \t\t"Field1": "cashback",\n        \t\t"Operator": "=",\n        \t\t"value": "10"\n        \t}]\n\t}]\n}',
        headers: {
            "Content-Type": "application/json"
        }
    });

    postman[Request]({
        name: "evaluate ruleset",
        id: "617fd3c1-7924-4467-9a84-a2f4e6d46751",
        method: "POST",
        address: "http://localhost:3000/api/v1/rulesets/_evaluate",
        data:
            '{\n\t"RulesetID": "ffc98ca2-ec55-4002-b688-5b6ca408da10",\n\t"Record": {\n\t\t"field1": 20\n\t}\n}',
        headers: {
            "Content-Type": "application/json"
        }
    });

    postman[Request]({
        name: "update ruleset",
        id: "cec9789f-fef3-4d04-aad9-ecc7c457f4fc",
        method: "PUT",
        address:
            "http://localhost:3000/api/v1/rulesets/ffc98ca2-ec55-4002-b688-5b6ca408da10",
        data:
            '{\n            "id": "ffc98ca2-ec55-4002-b688-5b6ca408da10",\n            "name": "ruleset2",\n            "StartDate": "2019-08-05T05:30:10+05:30",\n            "EndDate": "2019-08-05T05:30:10+05:30",\n            "Enable": true,\n            "Rules": [\n                {\n                    "id": "ef3b0a9e-ba19-4b4b-99f7-6ed145db8846",\n                    "name": "rule1",\n                    "Enable": true,\n                    "WhenConditions": [\n                        {\n                            "id": "cc1b4ba6-358e-4980-b388-eca70aed356a",\n                            "Field1": "age",\n                            "Field2": "35",\n                            "Operator": ">",\n                            "Threshold": ""\n                        },\n                        {\n                            "id": "ad56b3b8-62da-4d96-adcd-2890539c6779",\n                            "Field1": "interest",\n                            "Field2": [\n                                "reading",\n                                "music",\n                                "watching netflix"\n                            ],\n                            "Operator": "in",\n                            "Threshold": ""\n                        }\n                    ],\n                    "ThenActions": [\n                        {\n                            "id": "1b99fd10-3113-4511-894f-762814b8b129",\n                            "Field1": "cashback",\n                            "Value": "10"\n                        }\n                    ]\n                }\n            ]\n        }\n',
        headers: {
            "Content-Type": "application/json"
        }
    });

    postman[Request]({
        name: "get ruleset by id",
        id: "5fbad6dc-0963-47e4-bdc1-602395c8883f",
        method: "GET",
        address:
            "http://localhost:3000/api/v1/rulesets/ffc98ca2-ec55-4002-b688-5b6ca408da10"
    });
}
