database:
  url: "host=localhost port=5432 user=postgres dbname=candidates password=password sslmode=disable"
  name: "candidates"
  user: "admin"
  password: "your password"
  dialect: "postgres"
  mongoURL: "your mongo url"

server:
  host: "host name"
  port: 8080
